-- Vector store table removed — embeddings are not currently used.
-- All search uses PostgreSQL's built-in tsvector full-text search.
-- Original migration created a vector_store table with vector(1536) columns;
-- V18 would have dropped it. Both are now no-ops.
